### ISSUE TITLE
Exited -127

### ISSUE THREAD

**Issue by genxstylez** [rroemhild/docker-ejabberd#10]
Hi there,

I started using last week, running it as a daemon, but after a few days (3~4 days) the container exited with (-127) and had to restart it manually.

Can you help?

Thanks

**Comment by rroemhild** [comment]
Hey, can you provide some log messages?

**Comment by rroemhild** [comment]
Possibly related Docker issue: https://github.com/docker/docker/issues/5684

**Comment by rroemhild** [comment]
I close this for now. Please re-open this issue if you still have this problem. Regards
