### ISSUE TITLE
Problem with ssl

### ISSUE THREAD

**Issue by gavrmike** [rroemhild/docker-ejabberd#104]
Hi!

I would like to use docker-ejabberd with ssl.

I tried to run something like this:

```
docker run --restart=always -d \
    --name "ejabberd" \
    --user root \
    -v `pwd`/ssl:/opt/ejabberd/ssl \
    -p 5222:5222 \
    -p 5269:5269 \
    -p 5280:5280 \
    -h ps1.example.com \
    -e "XMPP_DOMAIN=ps1.example.com" \
    -e "ERLANG_NODE=ejabberd" \
    -e "EJABBERD_SSLCERT_HOST=/opt/ejabberd/ssl/ps1_example_com.pem" \
    -e "EJABBERD_SSLCERT_PS1_example_COM=/opt/ejabberd/ssl/ps1_example_com.pem" \
    -e "EJABBERD_CIPHERS=ALL:EECDH+aRSA+AESGCM:EDH+aRSA+AESGCM:EECDH+aRSA+AES:EDH+aRSA+AES" \
    -e "EJABBERD_PROTOCOL_OPTIONS_TLSV1=true" \
    -e "EJABBERD_ADMINS=admin@ps1.example.com admin2@ps1.example.com" \
    -e "EJABBERD_USERS=admin@ps1.example.com:password1234 admin2@ps1.example.com:password1234 user1@ps1.example.com:password1234 user2@ps1.example.com:password1234" \
    -e "TZ=Europe/Moscow" \
    rroemhild/ejabberd
```

But when i tried to open ps1.example.com:5280/http-bind, it doesnot open and in logs i see:

```
> 01:06:21.883 [error] CRASH REPORT Process <0.629.0> with 0 neighbours crashed with reason: no match of right hand value {error,<<"SSL_CTX_use_certificate_file failed: error:0906D06C:PEM routines:PEM_read_bio:no start line">>} in ejabberd_http:init/2 line 120
> 
```

ssl folder contains host.pem with hostname

```
cat host.pem 
ps1.example.com

```

and ps1.example.com.pem file
command:
`openssl x509 -text -in ps1.example.com.pem` works correctly

it looks like i forget setup some important environment variable, but i have no ideas and i need help

**Comment by rroemhild** [comment]
Hi, the environment vars `EJABBERD_SSLCERT_*` are used for the complete certificate an not for the cetificate filename. Certificate filenames uses dots instead of underscores.

Move your existing certificate from `ps1_example_com.pem` to `ps1.example.com.pem` and create a symlink from this xmpp-domain certificate to `host.pem` `ln -s ps1.example.com.pem host.pem`. Then remove the environment settings for `EJABBERD_SSLCERT_*` from start.

**Comment by gavrmike** [comment]
Thanks!

**Comment by rroemhild** [comment]
Port 5222 is for plain and STARTTLS. Port 5223 for the old SSL method. I disabled the old SSL method in the configuration file by default. To use this image with SSL you have to modify the config template ot use STARTTLS.
