### ISSUE TITLE
Can't seem to access web/websocket port

### ISSUE THREAD

**Issue by verma** [rroemhild/docker-ejabberd#110]
So I ran the image using the example command, but I cannot seem to get a response on `localhost:5280` while the other two ports seem to respond with xml which seems to be stream initiation requests.

Is there something specific I have to do to get websocket stuff to work, or even be able to see the admin interface?

**Comment by driminicus** [comment]
Have you tried going to http://localhost:5280/admin or https://localhost:5280/admin ?

**Comment by verma** [comment]
Oh! my bad, works on https 👍 thanks!
