### ISSUE TITLE
Disable SSL generation when running custom config?

### ISSUE THREAD

**Issue by rcoup** [rroemhild/docker-ejabberd#113]
Running a custom config file (by mounting `/opt/ejabberd/conf/ejabberd.yml`), we define SSL certificates/locations in there for our various domains. But the startup scripts still attempt to generate ssl certificates/dh params/etc, which fails on read-only secret mounts.

Could we skip SSL snakeoil generation/symlinking/everything if `$CONFIGFILE` already exists, since the user is presumably taking control of their config in that situation?

**Comment by driminicus** [comment]
I think the better way to do this is to check whether `/opt/ejabberd/ssl` is mounted as a volume, suggesting that the user wants to use his own cert.

**Comment by rcoup** [comment]
> I think the better way to do this is to check whether /opt/ejabberd/ssl is mounted as a volume, suggesting that the user wants to use his own cert

So if the directory is non-empty and the environment variables aren't set?

**Comment by driminicus** [comment]
That's what I would argue, but it's just my opinion.

**Comment by rroemhild** [comment]
Generation of SSL certificates should be skipped if they exists as in

https://github.com/rroemhild/docker-ejabberd/blob/master/scripts/pre/02_make_snakeoil_certificates.sh#L82

and

https://github.com/rroemhild/docker-ejabberd/blob/master/scripts/pre/02_make_snakeoil_certificates.sh#L88

for SSL certificates and

https://github.com/rroemhild/docker-ejabberd/blob/master/scripts/pre/03_make_dhparam.sh#L18

for DH.

**Comment by rcoup** [comment]
@rroemhild that only works if you have a pile of vhost certificates named correctly? In our case we have 1-2 certificates with SANs/wildcard certificates and a lot of vhosts.

**Comment by rroemhild** [comment]
My idea is to skip this with environment variables. Does #118 address your issue?

**Comment by rcoup** [comment]
>  Does #118 address your issue?
LGTM 👍

**Comment by rroemhild** [comment]
Great. #118 is merged into master. Thx!
