### ISSUE TITLE
Adding SSL files does not work without additional steps

### ISSUE THREAD

**Issue by jwred5** [rroemhild/docker-ejabberd#115]
I've made a derivative Dockerfile like so:

FROM rroemhild/ejabberd:15.07

#Add Active911 Config and PEM cert
ADD ./config/ejabberd.yml.tpl /opt/ejabberd/conf/ejabberd.yml.tpl
ADD ./config/active911.com.pem /opt/ejabberd/ssl/active911.com.pem

#Change permissions so ejabberd can read them
RUN chown ejabberd:ejabberd /opt/ejabberd/conf/ejabberd.yml.tpl
RUN chown ejabberd:ejabberd /opt/ejabberd/ssl/active911.com.pem

#We need the external auth scripts
ADD ./external_auth/ /usr/local/bin/xmpp-auth/

The image will not run because the /opt/ejabbed/ssl/active911.com.pem file is owned by root:root

Per http://stackoverflow.com/questions/26145351/why-doesnt-chown-work-in-dockerfile there is no way to change the permissions for this file because that folder is a Volume.

~~The only workaround is to change permissions of that file to be readable by all, ie chmod a+r /opt/ejabbed/ssl/active911.com.pem~~ EDIT: Actually this doesn't work either it seems.

The same is true for any files that would be added to a Volumized directory by the Dockerfile and needs to be read by ejabberd

**Comment by psi-4ward** [comment]
Yey that is correct.

I'll suggest a `scripts/pre/90-set-file-permissions.sh` with  
`chown -R $EJABBERD_USER: $EJABBERD_HOME`
