### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by flecno** [rroemhild/docker-ejabberd#12]
This docker image looks awesome, but on which git commit depends :latest pushed docker image? I ran in the same host/domain snakeoil typo, which is fixed on master. Can you release this docker images with tags, please?

Can your explain me the meaning of --adminpw? Is this password the login of admin@{{xmpp_host_name}}?

**Comment by rroemhild** [comment]
Your commit https://github.com/flecno/docker-ejabberd/commit/50604c18ac1d1fb35c47999467c9f17843945eb8 fixes this problem, please open a pull request.

Currently the docker image with the :latest tag is based on the master branch. To release images with tags is a god point.

The `--adminpw` option is for the first (admin) user you can provide with the `--admin` option and is required. In the ejabberd config we set an ACL for the admin user with a hostname based on the `XMPP_DOMAIN` ENV from the container.

With `--adminpw` the installer add a user withe the current hostname i.e. `admin@f7e33910641b` with the password `ejabberd`. This user has no admin rights in a running container. I should consider to clean the database directory on build so there is no unused user left.

**Comment by flecno** [comment]
Ah, thanks for the explanation about the `--admin` parameters. I'm going to open a PR for the host/domain part.
Tagging the docker images should be a really good part. What's about the tagging scheme `<ejabberd_version>-<docker_image_release`. So let's start with `14.12-1` tagged docker image and also git tag?

**Comment by rroemhild** [comment]
PR is merged and published to docker registry with the latest commits. I'll look into docker images tags and how to create them automated on `git push tag`. `14.12-1` looks good for tag name.

**Comment by rroemhild** [comment]
I started with a combination of release branch and update tags for the git repository and the docker images.
