### ISSUE TITLE
ejabberd 17.04 | several warnings during compiling

### ISSUE THREAD

**Issue by keyser-soeze** [rroemhild/docker-ejabberd#130]
Hi Rafael. I've cloned your Git repository and build the Docker image. After starting the Docker container from local Docker registry with `docker run ...` there are several warnings during compiling. Would be nice if you or the [ProcessOne team](https://github.com/processone/ejabberd) could fix these. These warnings appear also with ejabberd 17.03 version.

>Compiling c_src/sqlite3_drv.c
c_src/sqlite3_drv.c: In function ‘exec_async_command’:
c_src/sqlite3_drv.c:459:7: warning: too many arguments for format [-Wformat-extra-args]
       LOG_ERROR("driver_async call failed", 0);
       ^
c_src/sqlite3_drv.c:459:7: warning: too many arguments for format [-Wformat-extra-args]

> Compiled lib/dict.ex
lib/file/stream.ex:68: warning: behaviour Enumerable undefined

> Compiled lib/agent/server.ex
lib/hash_dict.ex:246: warning: behaviour Inspect undefined

> Compiled src/gen_pubsub_node.erl
src/mod_vcard.erl:34: Warning: undefined callback function reload/3 (behaviour 'gen_mod')

> Compiled src/pubsub_subscription_sql.erl
src/mod_shared_roster_ldap.erl:33: Warning: undefined callback function reload/3 (behaviour 'gen_mod')

> Compiled src/mod_offline_sql.erl
src/mod_http_upload.erl:63: Warning: undefined callback function reload/3 (behaviour 'gen_mod')

> Compiled src/mod_sic.erl
src/mod_mix.erl:28: Warning: undefined callback function reload/3 (behaviour 'gen_mod')

> Compiled src/mod_blocking_sql.erl
src/mod_http_upload_quota.erl:34: Warning: undefined callback function reload/3 (behaviour 'gen_mod')

> Compiled src/mod_muc_riak.erl
src/ejabberd_s2s_in.erl:23: Warning: undefined callback function bind/2 (behaviour 'xmpp_stream_in')
src/ejabberd_s2s_in.erl:23: Warning: undefined callback function check_password_digest_fun/1 (behaviour 'xmpp_stream_in')
src/ejabberd_s2s_in.erl:23: Warning: undefined callback function check_password_fun/1 (behaviour 'xmpp_stream_in')
src/ejabberd_s2s_in.erl:23: Warning: undefined callback function get_password_fun/1 (behaviour 'xmpp_stream_in')
src/ejabberd_s2s_in.erl:23: Warning: undefined callback function handle_timeout/1 (behaviour 'xmpp_stream_in')
src/ejabberd_s2s_in.erl:23: Warning: undefined callback function handle_unbinded_packet/2 (behaviour 'xmpp_stream_in')
src/ejabberd_s2s_in.erl:23: Warning: undefined callback function sasl_mechanisms/2 (behaviour 'xmpp_stream_in')

> Compiled src/ejabberd_s2s_in.erl
src/mod_service_log.erl:30: Warning: undefined callback function reload/3 (behaviour 'gen_mod')
Compiled src/mod_service_log.erl
src/ejabberd_c2s.erl:23: Warning: undefined callback function handle_stream_established/1 (behaviour 'xmpp_stream_in')
src/ejabberd_c2s.erl:23: Warning: undefined callback function handle_timeout/1 (behaviour 'xmpp_stream_in')

> Compiled src/ejabberd_piefxis.erl
src/ejabberd_s2s_out.erl:23: Warning: undefined callback function handle_authenticated_features/2 (behaviour 'xmpp_stream_out')
src/ejabberd_s2s_out.erl:23: Warning: undefined callback function handle_stream_start/2 (behaviour 'xmpp_stream_out')
src/ejabberd_s2s_out.erl:23: Warning: undefined callback function handle_unauthenticated_features/2 (behaviour 'xmpp_stream_out')

> Compiled src/mod_vcard_riak.erl
src/mod_pubsub.erl:35: Warning: undefined callback function reload/3 (behaviour 'gen_mod')

> Compiled src/mod_proxy65_stream.erl
src/ejabberd_service.erl:23: Warning: undefined callback function authenticated_stream_features/1 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function bind/2 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function check_password_digest_fun/1 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function check_password_fun/1 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function compress_methods/1 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function handle_call/3 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function handle_cast/2 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function handle_cdata/2 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function handle_recv/3 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function handle_send/3 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function handle_stream_end/2 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function handle_stream_established/1 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function handle_timeout/1 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function handle_unauthenticated_packet/2 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function handle_unbinded_packet/2 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function sasl_mechanisms/2 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function tls_enabled/1 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function tls_required/1 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function tls_verify/1 (behaviour 'xmpp_stream_in')
src/ejabberd_service.erl:23: Warning: undefined callback function unauthenticated_stream_features/1 (behaviour 'xmpp_stream_in')

> Compiled lib/ejabberd/hooks.ex
lib/mod_presence_demo.ex:1: warning: undefined behaviour function depends/2 (for behaviour :gen_mod)
lib/mod_presence_demo.ex:1: warning: undefined behaviour function mod_opt_type/1 (for behaviour :gen_mod)
lib/mod_presence_demo.ex:1: warning: undefined behaviour function reload/3 (for behaviour :gen_mod)

> Compiled lib/ejabberd/config/validator/validator_dependencies.ex
lib/ejabberd/config/logger/ejabberd_logger.ex:24: warning: variable val is unused

> Compiled lib/ejabberd/config/logger/ejabberd_logger.ex
lib/ejabberd/config/validator/validation.ex:10: warning: unused alias Attr
lib/ejabberd/config/validator/validation.ex:12: warning: unused alias ValidatorUtility

> Compiled lib/ejabberd/config/ejabberd_hook.ex
lib/ejabberd/config/validator/validator_attrs.ex:21: warning: variable attr is unused

> Compiled lib/ejabberd/config/opts_formatter.ex
lib/ejabberd/config/ejabberd_module.ex:15: warning: unused alias Attr

> Compiled lib/ejabberd/config/ejabberd_module.ex
lib/mix/tasks/deps.tree.ex:43: warning: variable mods is unused

**Comment by rroemhild** [comment]
Should be reported to the ejabberd team directly.
