### ISSUE TITLE
Update to the upcomging 17.08 version planned?

### ISSUE THREAD

**Issue by cwildfoerster** [rroemhild/docker-ejabberd#136]
Is an update to the upcomging 17.08 version planned. because the PR "Support XEP-0357: Push Notifications" just got merged.

**Comment by svenuthe** [comment]
+1

**Comment by svenuthe** [comment]
Depends on new Erlang OTP20, I guess.
But this is only available in Debian 9 (Stretch).
Hence, the first step should be to migrate container file to Debian 9.

**Comment by cwildfoerster** [comment]
i submitted a pr couple of days ago, updating to 17.08 and adding the official erlang repo

**Comment by Dunedan** [comment]
That PR is #144.

**Comment by rroemhild** [comment]
Merged into master.

**Comment by rroemhild** [comment]
Added branch and tags for 17.08
