### ISSUE TITLE
Multiple XMPP domains

### ISSUE THREAD

**Issue by rroemhild** [rroemhild/docker-ejabberd#14]
Possibility to set multiple XPMM Domains with XMPP_DOMAIN environment variable as mentioned by @slmingol in https://github.com/rroemhild/docker-ejabberd/pull/11#issuecomment-70249643.

**Comment by ligthyear** [comment]
No problem. I needed it, so edited the hosts-config part into the following:

```

##
## hosts: Domains served by ejabberd.
## You can define one or several, for example:
## hosts:
##   - "example.net"
##   - "example.com"
##   - "example.org"
##
{% set host_names=env.get('HOSTS', '').split(',') %}
hosts:
  - "{{ env['XMPP_DOMAIN'] or "chat.thegeoffrey.co" }}"
  {%- for host in host_names %}
  - "{host}"
  {%- endfor %}
```

Jinja2 for the WIN!

**Comment by rroemhild** [comment]
Yeah Jinja for the win. I have the same solution, with ssl cert generation for any domain if there is no certificate and multiple admins. I chose whitespace as the delimiter, i think it is easier to read and better to handle in bash script.

Regards
