### ISSUE TITLE
Switch to debian base image

### ISSUE THREAD

**Issue by rroemhild** [rroemhild/docker-ejabberd#15]
I consider to switch to `debian:7` base image. This will make the ejabberd docker image ~80MB smaller. The Ejabberd installer has Erlang binaries so we don't depend on the Erlang version from the apt repos.

**Comment by flecno** [comment]
This is a good point. I tried to build the image depending on debian which results in the images sizes:

from image | image size
---------- | ----------
debian:7 | 173.3 MB
debian:8 | 255.3 MB
ubuntu:14.04 | 253.7 MB

It's wondering how bigger debian 8 is...
Another option to reduce the image size is to explicit install python2.7, so debian doesn't install also 2.6. Results in ~150 MB.

Do we need `libyaml`? For me it looks like ejabberd has buildin support so we can remove the dependency too?

**Comment by rroemhild** [comment]
You are right `libyaml` is not longer needed and could be removed.

Debian supports wheezy until 2016 and maybe add another 2 years LTS support. For the meantime this should be fine for the ejabberd docker image. I'll add a `debian` branch for testing.
