### ISSUE TITLE
Using ejabberd.yml.tpl config file?

### ISSUE THREAD

**Issue by m-mital** [rroemhild/docker-ejabberd#150]
Hi
I'm tried to pass some variables to `ejabberd.yml` but it didn't work.
I found `ejabberd.yml.tpl` so I passed them to that file but it seems not working.

How I should change the configuration to start using `ejabberd.yml.tpl` template?

Thanks,

**Comment by m-mital** [comment]
Ok I know how it works. It just creates `ejabberd.yml` from `ejabberd.yml.tpl` when starting :)

**Comment by rroemhild** [comment]
Right. But you can link your own ejabberd.yml file to the container if you want, explained in https://github.com/rroemhild/docker-ejabberd#mount-configurations
