### ISSUE TITLE
Update packages from repo https://github.com/processone/ejabber {error,bad_eocd}

### ISSUE THREAD

**Issue by digitalstaub** [rroemhild/docker-ejabberd#163]
Hi,
sometime this message comes up on start and i have to restart. After restart its gone.

**Comment by jcho7022** [comment]
Same here would like to know what the problem is...

**Comment by jcho7022** [comment]
@mwlczk I'm starting Ejabberd using docker from an AWS ec2 instance. What might be the problem, in this case? Thank you.

**Comment by digitalstaub** [comment]
seems to be an erlang issue:
https://bugs.erlang.org/browse/ERL-196?jql=text%20~%20%22bad_eocd%22
