### ISSUE TITLE
docker-ejabberd and ejabberd deb

### ISSUE THREAD

**Issue by ravikantmishra** [rroemhild/docker-ejabberd#166]
Hello,

I need some help.

I have installed ejabberd 18.03 deb package on ubuntu from here (https://www.process-one.net/en/ejabberd/downloads/) and also enabled external auth with php script. Which is running successfully and no issues.

Now I am trying to use the same script with latest 18.03 "docker-ejabberd" and its not working. Error log says 

`10:07:07.584 [info] (<0.717.0>) Accepted connection ::ffff: 172.17.0.1:41628 -> ::ffff: 172.17.0.3:5222
10:08:07.587 [error] extauth call '[<<"auth">>,<<"admin">>,<<"xxxxxxxxxxxxx.com">>,<<"xxxxxxxxxxxxx">>]' didn't receive response`

Can somebody shed some light on what could be the possible issues.
 
Thanks in advance

**Comment by mitchellurgero** [comment]
Looks like your external auth script is not working as expected. Check there first.

**Comment by ravikantmishra** [comment]
@mitchellurgero 
ejabberd is able to execute php script because I can see all the logs that I have mentioned in the script.
this time php script is kept inside `/bin/index.php`
 
while earlier when I was using ejabberd without docker the script was kept inside `/var/www/html/index.php` and its was working. I was able to authenticate.

**Comment by ravikantmishra** [comment]
No i am not sending response in hex its just for logging purpose.

See the last line 
fwrite(..............

That line is being used to send response.

I also noticed that you are not using that line. While if you search all the PHP scripts available on the internet are using 
fwrite for sending response to ejabberd.

You sure we don't need that line?

**Comment by mitchellurgero** [comment]
Sorry - for context on my code:
https://github.com/mitchellurgero/ejabberd_gnusocial/blob/master/xmpp_auth.php

**Comment by ravikantmishra** [comment]
Thanks for all your support. I will try this.
