### ISSUE TITLE
How to connect from xmpp client on docker host?

### ISSUE THREAD

**Issue by joustava** [rroemhild/docker-ejabberd#170]
Hi thanks for this repo.
I'm trying out some different xmpp servers (playing around as I'm new to it) and this one seemed the easiest to get up and running.
The server runs with the default docker-compose example, and I can telnet to it with `telnet localhost 5222`. Only use case for now is just to run it locally.

But how would I connect to this from a xmpp client [profanity](https://github.com/boothj5/profanity) running on the docker host?

**Comment by rroemhild** [comment]
Hi, you have to set the servername (xmpp host) in the client config. Never used profanity but there should be a config option to do this.

**Comment by joustava** [comment]
Arg, I didn't realize jid domain part and server domain do not need to match and yes, profanity supports supplying the server separately [as per doc](http://www.profanity.im/reference.html#connect)

Thanks again!
