### ISSUE TITLE
Error  executing the ejabberd installer

### ISSUE THREAD

**Issue by LuisTJap** [rroemhild/docker-ejabberd#21]
Hi,
when i'm trying to build the image from the Dockerfile, in the installation step. If use directly the image from the registry all works well, do you know where could be the problem? I need to build the image cause i need to add something to the config file.
Thank you in advance,
Regards

**Comment by rroemhild** [comment]
Hey, please post the output from your build log and from `docker version`.

Regards

**Comment by LuisTJap** [comment]
of course! I'm using docker **1.4.1** And the log output is:
```
Step 12 : RUN wget -q -O /tmp/ejabberd-installer.run "http://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/$EJABBERD_VERSION/ejabberd-$EJABBERD_VERSION-linux-x86_64-installer.run"     && chmod +x /tmp/ejabberd-installer.run     && /tmp/ejabberd-installer.run             --mode unattended             --prefix $EJABBERD_ROOT             --adminpw ejabberd     && rm -rf /tmp/*     && mkdir $EJABBERD_ROOT/ssl     && rm -rf $EJABBERD_ROOT/database/ejabberd@localhost
 ---> Running in 4ab3c7bfd691
INFO[0067] The command [/bin/sh -c wget -q -O /tmp/ejabberd-installer.run "http://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/$EJABBERD_VERSION/ejabberd-$EJABBERD_VERSION-linux-x86_64-installer.run"     && chmod +x /tmp/ejabberd-installer.run     && /tmp/ejabberd-installer.run             --mode unattended             --prefix $EJABBERD_ROOT             --adminpw ejabberd     && rm -rf /tmp/*     && mkdir $EJABBERD_ROOT/ssl     && rm -rf $EJABBERD_ROOT/database/ejabberd@localhost] returned a non-zero code: 1 
```
Thank you for your quick answer

**Comment by rroemhild** [comment]
I can reproduce this behaviour on an `Ubuntu 12.04.5` System with `Docker 1.4.1` and `AUFS` storage driver. You can try to build the image with the `devicemapper` storage driver => http://muehe.org/posts/switching-docker-from-aufs-to-devicemapper

But you don't need to build the entire image by yourself to use your own configuration files. Use this image as the base image and copy your configfiles => https://github.com/rroemhild/docker-ejabberd#using-docker-ejabberd-as-base-image

Regards,
Rafael

**Comment by LuisTJap** [comment]
Ok, i used you image as my base image and all works well, thank you very much, if i need to compile the image for some reason i will do it as you say, thank you again, you save a lot of time with your work!

**Comment by rroemhild** [comment]
You're welcome!
