### ISSUE TITLE
Cannot enter ejabberd debug

### ISSUE THREAD

**Issue by dirkmoors** [rroemhild/docker-ejabberd#24]
While experimenting with a your docker image as a base image, I noticed that It was impossible for me to go into ejabberdctl debug mode?

My use case for this is the configuration of a multi-master fault tolerant cluster (based on http://chad.ill.ac/post/55193155663/easy-ejabberd-clustering-multi-master-fault), which I want to automate as much as possible.

If i run 'docker exec -ti jabber ejabberdctl debug', the command 'freezes' until I press CTRL-C.

If I would be possible to define a cluster during docker build time, or via the 'run' script, it would be awesome because I would't need the debug shell then...

**Comment by rroemhild** [comment]
I can confirm that the debug shell can not attach to the running node. I'll take a look at this and automating the cluster setup is an interesting feature for this image.

To experiment with the shell you can run the container in [foreground](https://github.com/rroemhild/docker-ejabberd#run-in-foreground-with-attached-erlang-shell) or in background and attach to the container:

```
$ docker run -dit --name "ejabberd" -P rroemhild/ejabberd live
$ docker attach ejabberd
```
