### ISSUE TITLE
Automatically provisioning administrator(s)

### ISSUE THREAD

**Issue by dirkmoors** [rroemhild/docker-ejabberd#25]
I would like to automatically provision administrator(s) while deploying or starting the docker image.
I would not mind adding username and password for the administrator(s) in the docker file or in the environment variables of the docker hosts. 

I'm running into a 'chicken or the egg' problem here;
If I add exec 'ejabberdctl register admin domain passwd' before the ejabberd is running, It fails. If I want to run it afterwards, I can't run it because the ejabberd server is blocking...

Could you point out how I can facilitate such use case with this docker image/run script?

**Comment by rroemhild** [comment]
Give ejabberd time to start before register administrator(s).

```
case "$@" in
    start)
        [...]
        exec ${EJABBERDCTL} "live" &
        child=$!
        sleep 3
        ${EJABBERDCTL} register admin example.de password1234

```

**Comment by dirkmoors** [comment]
That seems to have worked, thanks!

**Comment by dirkmoors** [comment]
I was a bit too quick there. This solution works when running the docker with:

docker run -i -t rroemhild/docker-ejabberd

The problem is, when I try to do 'docker start <CONTAINER_ID>' afterwards, it crashes right away.

Do you know what's going on?

**Comment by rroemhild** [comment]
In the second line from the run script `set -e` immediately exit the script on errors. `ejabberdctl register` returns an error on `docker start` because the admin user is already registered. To test this you can comment in line 2 and re-build the image. I would prefer a function that test if the container is provisioned and then skip register the admin user(s).

**Comment by dirkmoors** [comment]
Yeah commenting out 'set -e' fixed my problem. Maybe create a feature request for adding provisioning of a 'superuser' during build/deploy time?

**Comment by rroemhild** [comment]
My idea for this is to split the run script into multiple pre- and post- run scripts. With this solution you can extend this image with a script that i.e. register admin users or as in #24 setup a cluster.

I pushed a preview to the `split-run-script` branch and add a sample script `20_ejabberd_register_admin.sh` to `scripts/post`. To enable pre/post scripts they need an `x` flag. Run `chmod +x 20_ejabberd_register_admin.sh` and build the image.

**Comment by dirkmoors** [comment]
That looks very nice, I'll give it a go asap!
