### ISSUE TITLE
Automate cluster joining

### ISSUE THREAD

**Issue by dirkmoors** [rroemhild/docker-ejabberd#31]
# It would be an awesome feature to be able to automatically join a cluster of ejabberd nodes.

*Some basic but important info can be found here http://docs.ejabberd.im/admin/guide/clustering/*

## 1. Providing nodes via ENV or extra config file?
It seems doable and fairly easy?

I could image a scenario where I would make a private docker image based on 'docker-ejabberd', where I would provide a file 'extra-hosts', which looks like /etc/hosts, e.g.:

    192.168.1.10 service1 service1-alias
    192.168.1.11 service2 service2-alias
    192.168.1.12 service3 service3-alias

During docker build-time, this file would simply be copied inside the docker image to a file, e.g. /etc/extra-hosts (maybe configurable via an environment variable like $EXTRA_HOSTS_FILE?).

At run time, a shell script would check for the existence of $EXTRA_HOSTS_FILE, and if it exists, copy all lines to /etc/hosts, and if needed, reload the local DNS resolving.

This would allow for manually joining a cluster, because all nodes are now able to connect to the other nodes, based on their hostnames:

```bash
# At the node 'ejabberd@service1', I would call the following:
$ ejabberdctl join_cluster 'ejabberd@service2'
$ ejabberdctl join_cluster 'ejabberd@service3'

# At the node 'ejabberd@service2', I would call the following:
$ ejabberdctl join_cluster 'ejabberd@service1'
$ ejabberdctl join_cluster 'ejabberd@service3'

# At the node 'ejabberd@service3', I would call the following:
$ ejabberdctl join_cluster 'ejabberd@service1'
$ ejabberdctl join_cluster 'ejabberd@service2'
```

## 2. Automatically joining the cluster, based on ENV or extra config file?
Given the fact the we're able to connect to the other nodes, based on their hostnames (see previous topic), it should be doable to automatically join a cluster, based on supplied ENV variables or an extra config file

Imagine the following config file: ./conf/cluster, containing a node definition on each line:
    
    ejabberd@service1
    ejabberd@service2
    ejabberd@service3

A post run script could then iterate over these node definitions, and if it discovers it is a remote node, call the 'ejabberdctl join_cluster *node*' command.

I believe this would be a straightforward way to automate the last step of the previous topic.

### Remarks: 
* 'race condition' danger
  - Nodes could be still booting when the automatic joining is being performed, making the joining fail. This could be overcome by retrying to join after a failed attempt?
* Discovering other nodes dynamically?
  - Out of scope, and probably not that easy...

**Comment by dirkmoors** [comment]
Since I'm not  very skilled in bash scripting, it will be very hard for me to actually implement this.
If we would do it with python or something, it would not be a problem, but bash script is just magic for me :)

**Comment by rroemhild** [comment]
I just pushed my cluster test to the [cluster branch](https://github.com/rroemhild/docker-ejabberd/tree/cluster) but run into another problem. I published it so you can take a look.

For topic 1 I think this could be solved with tools like [kubernetes](http://kubernetes.io/) or the [Docker Orchestrating](http://blog.docker.com/2015/02/orchestrating-docker-with-machine-swarm-and-compose/) tools. They should handle the container linking, like docker-compose does.

Another solution for this could be [etcd](https://github.com/coreos/etcd#etcd) from the CoreOS people. Etcd running in an extra container and every docker-ejabberd container announce itself to `etcd` and look out for a master node in `etcd`. I think to manual announce hosts, `etcd` is a solid solution for topic 1. This could also be achieved with an redis instance or something else, if orchestrating is not an option.

I will think about automating clustering the next days, it is a new topic for me.

**Comment by rroemhild** [comment]
I'm getting closer :smile:

With some work around the issues https://github.com/processone/ejabberd/issues/498 and https://github.com/processone/ejabberd/issues/497 I get an two node cluster up and running with `docker-compose`. See [cluster branch](https://github.com/rroemhild/docker-ejabberd/tree/cluster).

**Comment by dirkmoors** [comment]
Cool!

Is this 'multiple master' or 'master-slave'? And does this work across physical hosts (e.g. multiple different physical machines, probably in the same network private though)?

**Comment by rroemhild** [comment]
This is an 'multiple master' cluster, but only with two hosts because `docker-compose` can't cross-link container. I'm thinking and experimenting with an elegant host/node auto discover solution.

If the physical machines can talk to each other on the required ports it should work in the same network or over multiple locations.

I've setup a tutum.co and aws account to test the cluster feature in a real world scenario.

**Comment by dirkmoors** [comment]
Awesome, I'm looking forward to your findings!

**Comment by rroemhild** [comment]
Finally I've add an [example](https://github.com/rroemhild/docker-ejabberd/tree/master/examples/docker-compose) how this image could be used to setup a multi-node cluster based on different tools.

On tutum i.e. you can't set dnsname and nameservers, but you can start with the scripts in this example or write your own start-scripts and use the tools provided by tutum.

**Comment by were-oyomno** [comment]
Do you have a working example on how cluster ejabberd containers auto?
I would be interested in seeing you accomplished that.

**Comment by rroemhild** [comment]
You can start with the [compose-cluster example](https://github.com/rroemhild/docker-ejabberd/tree/master/examples/docker-compose-cluster).

**Comment by dorsegal** [comment]
I know this is old thread but is this solution is good for multi hosts?
host1 - ejabberd@node1
host2 - ejabberd@node2

**Comment by Joginder22** [comment]
I've deployed ejabberd cluster on k8s by taking examples from the scripts used by rroemhild. but i observed that after 10 requests container was failing. After lot of tweeks i found when i used containers with host-network, it worked fine. although it is working fine as of now. I'm not sure what was the actual cause of cluster not accepting more requests. I've tried using 3 and 5 node cluster. 

Below was the error i was getting for more than 10 requests without using host-network for containers: 
INFO: Starting with 1 request processors
Dec 19, 2017 6:36:23 PM org.jivesoftware.smack.AbstractXMPPConnection callConnectionClosedOnErrorListener
WARNING: Connection XMPPBOSHConnection[not-authenticated] (4) closed with error
org.igniterealtime.jbosh.BOSHException: Could not obtain response
	at org.igniterealtime.jbosh.ApacheHTTPResponse.awaitResponse(ApacheHTTPResponse.java:246)
	at org.igniterealtime.jbosh.ApacheHTTPResponse.getBody(ApacheHTTPResponse.java:187)
	at org.igniterealtime.jbosh.BOSHClient.processExchange(BOSHClient.java:1114)
	at org.igniterealtime.jbosh.BOSHClient.processMessages(BOSHClient.java:990)
	at org.igniterealtime.jbosh.BOSHClient.access$300(BOSHClient.java:100)
	at org.igniterealtime.jbosh.BOSHClient$RequestProcessor.run(BOSHClient.java:1719)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.NoHttpResponseException: 1

**Comment by Hayyk** [comment]
@Joginder22 Any working example of cluster on k8s?

**Comment by Joginder22** [comment]
I have setup it in our cloud. What is required? tell me.

**Comment by Hayyk** [comment]
@Joginder22 How did you solve the ejabberd nodes joining cluster in k8s cluster?
I've done that using pod DNS settings, but I believe there is a more elegant way to do that

**Comment by Hayyk** [comment]
Hi @Joginder22 
thanks for your reply. it's very similar to my configuration. I'm using pod dns setting which is available on k8s starting 1.10+ in beta version but how you are making new nodes to autojoin cluster? I did it this way:
1. added root ejabberd node as separate pod
2. created replicaset which takes control of this node and creates new nodes based on predefined params
3. used script inside container to connect to root node once ejabberd started
This allows to scale replica set up and down and new nodes are automatically joining the existing cluster aka ejabberd root node.

**Comment by Hayyk** [comment]
@Joginder22 unfortunately I have some issues, when new node joins the cluster, it hangs without any error or warning log until ejabberd restarted. I want to resolve this issue. any idea why this can happen?

**Comment by claudiocleberson** [comment]
Hi @Hayyk  @Joginder22

Let me ask you guys!  have you solved the issues with the cluster nodes joining automatically the cluster?

I was looking for an implementation on kubernetes for ejabberd. unfortunatelly there ins't much documented. After some blogs and also the discussion you guys had here, I'm now able to deploy a cluster of  ejabberd nodes that join automatically. there some improvements that can be made. Like join the cluster if the connection with the cluster has been lost, but over all the implementation is easy to replicate.

I am going to suggest to @rroemhild  that implementation documentation to be available here. I think that would be a great to people on the community  who use ejabberd and are migrating to a Kubernetes env.
