### ISSUE TITLE
modules_update_specs does not always succeed

### ISSUE THREAD

**Issue by rhalukongor** [rroemhild/docker-ejabberd#36]
Sometimes (2 out of 3 times may be) post install script fails with error:
````
Updating module specs... 09:48:22.560 [info] Application p1_iconv started on node ejabberd@localhost
Error: command "modules_update_specs" not known.
````
Also i noticed that when the `p1_iconv started` log entry is **before** the `Updating module specs` entry the script succeeds. Need some delay may be?

I'm on OS X (boot2docker) BTW; however I also observe the same behaviour on an Ubuntu server.

**Comment by rroemhild** [comment]
This hopefully was fixed with 21bac1d50ec5ddb5feb21338308a7aed53f713fe. Did you test this with the latest image from docker index or build by yourself?

**Comment by rhalukongor** [comment]
I've been using the image from docker index; will try building myself. Thanks a lot for the info.

**Comment by rroemhild** [comment]
You're welcome. This should also work with the latest `rroemhild/ejabberd:latest` build from docker index.

**Comment by rhalukongor** [comment]
Off topic: Which is the best place install modules.
I've tried pre install script; fails with erlang nodedown because ejabberd is not started yet.
Any other option involving ejabberdctl restart is out of question since docker container would quit.
This is coming from someone with no erlang experience at all :)

**Comment by rroemhild** [comment]
Modules get installed in `/opt/ejabberd/.ejabberd-modules`. To automate module installation you have to run one or more post scripts after module update spec i.e. `40_install_modules.sh`

```shell
#!/bin/bash
set -e

source "${EJABBERD_HOME}/scripts/lib/base_config.sh"
source "${EJABBERD_HOME}/scripts/lib/config.sh"
source "${EJABBERD_HOME}/scripts/lib/base_functions.sh"
source "${EJABBERD_HOME}/scripts/lib/functions.sh"

${EJABBERDCTL} module_install mod_admin_extra
```

You can test this inside a running container:

```shell
$ docker exec -it <containerid> ejabberdctl modules_available
$ docker exec -it <containerid> ejabberdctl module_instakk mod_admin_extra
```

**Comment by rhalukongor** [comment]
I beileve the way you've suggested requires an ejabberdctl restart which causes container to exit. Tried your suggestion + uncommenting (initially commented out) sections related to modules installed via sed and reload_config instead of restart; also doesn't work. I was thinking of VOLUME'ing yml file, so it stays intact after a restart however I can't imagine a production scenario if I do that. Any suggestions?

**Comment by rhalukongor** [comment]
Sorry to bug you up until now. It all boils down to Ejabberd and its -not so ready for docker- module system. A relevant discussion is here: https://github.com/processone/ejabberd/issues/487 for anyone stops by.
