### ISSUE TITLE
SSL/TLS handshake error

### ISSUE THREAD

**Issue by nikriek** [rroemhild/docker-ejabberd#43]
Hi, I'm using your repo for testing purposes on my Mac. When establishing a connection from a client, this error is thrown:
```
21:09:14.469 [error] TLS error = SSL_do_handshake failed: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
```
Per command line argument I forwarded these ports:
* 5222:5222
* 5269:5269
* 5280:5280
* 5223:5223 

As I am not so experienced with Docker yet, this can also be a configuration fault…

**Comment by nikriek** [comment]
Ok, I solved it myself. I switched from Psi to Adium…

**Comment by miracle2k** [comment]
I have the same problem now; a previous version of docker-ejabberd (or more likely the culprit, ejabberd) didn't have an issue with Psi.

**Comment by miracle2k** [comment]
Presumably it is related to this: https://github.com/rroemhild/docker-ejabberd/commit/741b8357d34e005267d2a87b58cc24cd46930c1e

I'm no SSL expert, but Psi hasn't been updated in a long time.

**Comment by rroemhild** [comment]
I think this is an issue with older OS X versions. Does it work if you re-enable TLSv1?

**Comment by miracle2k** [comment]
It is not exclusive to OSX, I have the problem one various versions of Windows as well.

I renabled both TLSv2 and SSL3 (made harder by the fact that I couldn't figure out a simple way to modify the config file in the running container for testing a changed config), and the SSL problem is gone.

Now a separate problem appeared with Psi, immediately after login:

     2015-06-17 10:35:46.899 [error] <0.617.0> CRASH REPORT Process <0.617.0> with 0 neighbours exited with reason: bad argument in call to xml:element_to_binary({xmlel,<<"message">>,[{<<"from">>,<<"michael@foo.com">>},{<<"to">>,<<"annemarie@foo....">>},...],...}) in ejabberd_c2s:send_element/2 line 1908

This is on OSX, I will try some Windows.

**Comment by miracle2k** [comment]
Ok, the relevant bug report in ejabberd is here: https://github.com/processone/ejabberd/issues/479
