### ISSUE TITLE
"This account is currently not available." after update from lxc-docker 1.6.2 to 1.7.0

### ISSUE THREAD

**Issue by chrissearle** [rroemhild/docker-ejabberd#49]
Trying to run

    docker exec ejabberd ejabberdctl

Kept getting "This account is currently not available."

If I use

    docker exec ejabberd chsh /bin/bash/ejabberd

to change the ejabberd shell from nologin to bash then I can docker exec ejabberdctl without issue.

Happened after updating docker from 1.6.2 to 1.7 (debian wheezy images from docker's repo). Not found anything yet on whether this is intentional in 1.7 - but - I thought I'd mention that it seems to break exec with nologin and therefore ejabberdctl for me.

**Comment by rroemhild** [comment]
Docker 1.7 introduce the -u|--user flag to specify the new process owner. But I think it is ok to enable the ejabberd account.
