### ISSUE TITLE
Permission problem with volumes

### ISSUE THREAD

**Issue by dirkmoors** [rroemhild/docker-ejabberd#57]
I'm currently facing problems when I try to mount a volume onto /opt/ejabberd/database.
What happens is this:

During the docker build phase, we create a directory $EJABBERD_HOME/database, chown it to user 'ejabberd', and we make a volume for this directory:
```
VOLUME ["$EJABBERD_HOME/database", "$EJABBERD_HOME/ssl"]
```

Afterwards, I try to start the container like this:
```
docker run -ti -p "4560:4560" -p "5280:5280" \
    -e "EJABBERD_REGISTER_TRUSTED_NETWORK_ONLY=true" \
    -e "EJABBERD_ADMIN=admin@example.com" \
    -e "EJABBERD_ADMIN_PWD=admin" \
    -e "XMPP_DOMAIN=example.com" \
    -e "EJABBERD_MUC_CREATE_ADMIN_ONLY=true" \
    -e "EJABBERD_REGISTER_ADMIN_ONLY=true" \
    -e "EJABBERD_MOD_ADMIN_EXTRA=true" \
    -e "EJABBERD_MOD_MUC_ADMIN=true" \
    -e "EJABBERD_WEB_ADMIN_SSL=false" \
    -e "EJABBERD_S2S_SSL=true" \
    -v /tmp/ejabberd/database:/opt/ejabberd/database
    docker-ejabberd
```
But the server won't start:
```
Missing ssl cert for your host. Generating snakeoil ssl cert for localhost...
Generating a 2048 bit RSA private key
.............+++
...+++
writing new private key to '/tmp/selfsigned.key'
-----
Writing ssl cert and private key to '/opt/ejabberd/ssl/host.pem'...
Missing ssl cert for your xmpp domain. Generating snakeoil ssl cert for example.com...
Generating a 2048 bit RSA private key
.....+++
..............................................................+++
writing new private key to '/tmp/selfsigned.key'
-----
Writing ssl cert and private key to '/opt/ejabberd/ssl/example.com.pem'...
Generating ejabberd config file...
Generating ejabberdctl config file...
Starting ejabberd...
tail: cannot open ‘/var/log/ejabberd/crash.log’ for reading: No such file or directory
tail: cannot open ‘/var/log/ejabberd/error.log’ for reading: No such file or directory
tail: cannot open ‘/var/log/ejabberd/erlang.log’ for reading: No such file or directory
mkdir: cannot create directory ‘/opt/ejabberd/database/ejabberd@localhost’: Permission denied
/sbin/ejabberdctl: 154: cd: can't cd to /opt/ejabberd/database/ejabberd@localhost
mkdir: cannot create directory ‘/opt/ejabberd/database/ejabberd@localhost’: Permission denied
/sbin/ejabberdctl: 154: cd: can't cd to /opt/ejabberd/database/ejabberd@localhost
tail: ‘/var/log/ejabberd/crash.log’ has been replaced with a remote file. giving up on this name
tail: ‘/var/log/ejabberd/error.log’ has been replaced with a remote file. giving up on this name
17:41:16.728 [info] Application lager started on node ejabberd@localhost
17:41:16.731 [info] Application crypto started on node ejabberd@localhost
17:41:16.736 [info] Application sasl started on node ejabberd@localhost
17:41:16.740 [info] Application asn1 started on node ejabberd@localhost
17:41:16.740 [info] Application public_key started on node ejabberd@localhost
17:41:16.744 [info] Application ssl started on node ejabberd@localhost
17:41:16.746 [info] Application p1_yaml started on node ejabberd@localhost
17:41:16.751 [info] Application p1_tls started on node ejabberd@localhost
17:41:16.754 [info] Application p1_xml started on node ejabberd@localhost
17:41:16.755 [info] Application p1_stringprep started on node ejabberd@localhost
17:41:16.757 [info] Application p1_zlib started on node ejabberd@localhost
17:41:16.758 [info] Application p1_cache_tab started on node ejabberd@localhost
17:41:16.798 [info] Application mnesia started on node ejabberd@localhost
17:41:17.280 [info] FQDN used to check DIGEST-MD5 SASL authentication: 872a9630aed3
17:41:17.300 [info] Application inets started on node ejabberd@localhost
17:41:17.302 [error] CRASH REPORT Process <0.38.0> with 0 neighbours exited with reason: {aborted,{no_exists,passwd,attributes}} in application_master:init/4 line 133
17:41:17.303 [info] Application ejabberd exited with reason: {aborted,{no_exists,passwd,attributes}}
```
The error I see happening is:
```
mkdir: cannot create directory ‘/opt/ejabberd/database/ejabberd@localhost’: Permission denied
```

**Comment by dirkmoors** [comment]
Possible duplicate of: https://github.com/docker/docker/issues/3124

**Comment by dirkmoors** [comment]
What I understand is that Docker considers 'bind-mounts' as being owned by 'root' user.

**Comment by dirkmoors** [comment]
@rroemhild Would you consider it an option to change the user to 'root'?

**Comment by rroemhild** [comment]
Run ejabberd with the root user removes a bit of security. What about change the directory owner:group to the ejabberd id (999) or set read/write permissions for others?

**Comment by rroemhild** [comment]
Or use a data-container and set the correct ownership:
```
$ docker create -v /opt/ejabberd/database -v /opt/ejabberd/ssl --name ejabberd-data debian
$ docker run --rm --volumes-from ejabberd-data debian chown -R 999:999 /opt/ejabberd
$ docker run -d --name ejabberd --volumes-from ejabberd-data rroemhild/ejabberd
```

**Comment by dirkmoors** [comment]
@rroemhild I would rather not work with a data container (although it SHOULD be possible ofcourse), since I want to make sure the data persists in production. Changing directory permissions on the host to a user that only exists in a container seems counter-intuitive. If there would be a way for the non-root user to write a mounted directory on the host, that would work for me too. In the meanwhile, I'm pretty much stuck...

**Comment by sunsided** [comment]
Heya. I stumpled over this very sample problem. Since you already use startup scripts, I'd like to suggest something like the following:

We could have a `EJABBERD_UID` environment variable, possibly preset to `999` in the `Dockerfile`. On `run` - as `root` - perform a

    usermod -u $EJABBERD_UID $EJABBERD_USER

to change the `ejabberd` user's UID on the fly. The permissions on all owned directories and files should be changed automatically. After that, continue on as `$EJABBERD_USER`. 

I assume it might also be possible to install `sudo` in the dockerfile, add a `change-user.sh` script that does the above and then configure passwordless `sudo` access to this file only, removing the need to run as `root` if that isn't feasible.

**Comment by rroemhild** [comment]
@sunsided thanks for your contribution You got me on the right track. Can you both review the PR please. The container must be started with the `-u root` option.

**Comment by rroemhild** [comment]
I merged the PR to master branch. It works for me and I think it addresses this problem by let the user decide to run ejabberd as `root` but run with `ejabberd` user by default. Feel free to re-open this issue.
