### ISSUE TITLE
Docker registry: add multiple releases

### ISSUE THREAD

**Issue by dirkmoors** [rroemhild/docker-ejabberd#63]
I'm currently working on a Python library (https://github.com/dirkmoors/pyejabberd) that implements the Ejabberd XMLRPC api. I would like to perform integration tests against multiple versions of Ejabberd. Could you please add more releases to your Docker registry? I'm testing against the branches currently, and now that is only 15.06 and latest.

Thanks in advance!

**Comment by rroemhild** [comment]
Great use case for this docker image. Docker registry releases are now up to date and pushed.

**Comment by dirkmoors** [comment]
Awesome!
