### ISSUE TITLE
Getting error "name seems to be in use by another erlang node"

### ISSUE THREAD

**Issue by bingopne** [rroemhild/docker-ejabberd#64]
Hi,
I was trying to create a cluster of two ejabberd node running the same domain using ejabberd docker container:

docker run -d \

    --name "ejabberd1" -v /etc/hosts:/etc/hosts \

    -h 'node1.example.de' \

    -e "XMPP_DOMAIN=example.de" \

    -e "ERLANG_NODE=ejabberd1@node1.example.de" \

    -e "TZ=Europe/Berlin" \

    rroemhild/ejabberd

docker run -d \

    --name "ejabberd2" -v /etc/hosts:/etc/hosts \

    -h 'node2.example.de' \

    -e "XMPP_DOMAIN=example.de" \

    -e "ERLANG_NODE=ejabberd2@node2.example.de" \

    -e "TZ=Europe/Berlin" \

    rroemhild/ejabberd

 but it is giving me the following error, while joining the node2 node from node1:

ejabberdctl join_cluster 'ejabberd1@node1.example.de'

{error_logger,{{2015,8,3},{9,34,15}},"Protocol: ~tp: the name ejabberd2@node2.example.de seems to be in use by another Erlang node",["inet_tcp"]}

{error_logger,{{2015,8,3},{9,34,15}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.20.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,322}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.99>,<0.17.0>]},{dictionary,[{longnames,true}]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,750}],[]]}

{error_logger,{{2015,8,3},{9,34,15}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[['ejabberd2@node2.example.de',longnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}

{error_logger,{{2015,8,3},{9,34,15}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}

{error_logger,{{2015,8,3},{9,34,15}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,117}],[]]}

{error_logger,{{2015,8,3},{9,34,15}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}

{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}}"}

Crash dump was written to: //var/log/ejabberd/erl_crash_20150803-093414.dump

Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k

root@node2:~# root@boot2docker:~# Connection to localhost closed by remote host.

error in run: exit status 255

Would be thankful if any help can be provided to resolve it.

**Comment by bingopne** [comment]
Issue gets resolved by first joining the cluster and then starting the current node.

**Comment by rroemhild** [comment]
Greate you solved it, had no time to look at this. Regards
