### ISSUE TITLE
How to import an ejabberd dump?

### ISSUE THREAD

**Issue by Dinduks** [rroemhild/docker-ejabberd#65]
Hi,

Is it possible to load my dump created from my previous installation with `ejabberdctl dump`?
Also, is it possible to store the whole configuration in my host, for better portability?

Thank you.

**Comment by rroemhild** [comment]
Hi,

to store your own configuration you can use this image as  base-image and overwrite the config-template-files:

```
FROM rroemhild/ejabberd
ADD ./ejabberd.yml /opt/ejabberd/conf/ejabberd.yml.tpl
ADD ./ejabberdctl.cfg /opt/ejabberd/conf/ejabberdctl.cfg.tpl
```

To restore from your previous installation you have to copy the dumpfile to a running container with `docker cp` by hand and restore from the webgui or with the ejabberdctl tool, but I've not tested this yet.

I can add an startup restore script to automate this. Maybe by pulling the dumpfile with curl from an URL defined in the environment. Would this be helpful?

**Comment by rroemhild** [comment]
If add a [Maintenance](https://github.com/rroemhild/docker-ejabberd#maintenance) section to readme for `backup` and `restore`. This should also work for `dump` and `load`, but I've not tested this yet. Feel free to reopen this issue. Regards.

**Comment by Dinduks** [comment]
I didn't have the opportunity to try this, but I wanted to thank you. :bow:
