### ISSUE TITLE
 Cannot run docker image.

### ISSUE THREAD

**Issue by patrickcorrigan** [rroemhild/docker-ejabberd#73]
When trying to start the docker images using

docker run -t -i -p 5222 -p 5269 -p 5280 -e "XMPP_DOMAIN=foo.com" rroemhild/ejabberd

I get the following output and then the container stops. Am I missing something? Thank you very much for your help.

```
patrick@tesla ...code/musica/ejabber %  docker run -t -i -p 5222 -p 5269 -p 5280 -e "XMPP_DOMAIN=foo.com" rroemhild/ejabberd
Missing ssl cert for your host. Generating snakeoil ssl cert for 291d27d74100...
Generating a 2048 bit RSA private key
...................................................+++
...........+++
writing new private key to '/tmp/selfsigned.key'
-----
Writing ssl cert and private key to '/opt/ejabberd/ssl/host.pem'...
Missing ssl cert for your xmpp domain. Generating snakeoil ssl cert for foo.com...
Generating a 2048 bit RSA private key
...................................................................................+++
.........................................................+++
writing new private key to '/tmp/selfsigned.key'
-----
Writing ssl cert and private key to '/opt/ejabberd/ssl/foo.com.pem'...
Generating ejabberd config file...
Generating ejabberdctl config file...
Starting ejabberd...
tail: cannot open ‘/var/log/ejabberd/crash.log’ for reading: No such file or directory
tail: cannot open ‘/var/log/ejabberd/error.log’ for reading: No such file or directory
tail: cannot open ‘/var/log/ejabberd/erlang.log’ for reading: No such file or directory
tail: ‘/var/log/ejabberd/crash.log’ has appeared;  following end of new file
tail: ‘/var/log/ejabberd/error.log’ has appeared;  following end of new file
14:58:58.749 [info] Application lager started on node ejabberd@291d27d74100
14:58:58.756 [info] Application crypto started on node ejabberd@291d27d74100
14:58:58.771 [info] Application sasl started on node ejabberd@291d27d74100
14:58:58.788 [info] Application asn1 started on node ejabberd@291d27d74100
14:58:58.788 [info] Application public_key started on node ejabberd@291d27d74100
14:58:58.804 [info] Application ssl started on node ejabberd@291d27d74100
14:58:58.810 [info] Application p1_yaml started on node ejabberd@291d27d74100
14:58:58.820 [info] Application p1_tls started on node ejabberd@291d27d74100
14:58:58.826 [info] Application p1_xml started on node ejabberd@291d27d74100
14:58:58.831 [info] Application p1_stringprep started on node ejabberd@291d27d74100
14:58:58.835 [info] Application p1_zlib started on node ejabberd@291d27d74100
14:58:58.839 [info] Application p1_cache_tab started on node ejabberd@291d27d74100
14:58:58.976 [info] Application mnesia started on node ejabberd@291d27d74100
14:58:59.425 [info] Application inets started on node ejabberd@291d27d74100
14:58:59.967 [info] FQDN used to check DIGEST-MD5 SASL authentication: 291d27d74100
14:59:00.011 [info] Application oauth2 started on node ejabberd@291d27d74100
14:59:00.057 [info] Application p1_iconv started on node ejabberd@291d27d74100
14:59:00.278 [info] Reusing listening port for {4560,{0,0,0,0},tcp}
14:59:00.279 [info] Reusing listening port for {5222,{0,0,0,0},tcp}
14:59:00.279 [info] Reusing listening port for {5269,{0,0,0,0},tcp}
14:59:00.279 [info] Reusing listening port for {5280,{0,0,0,0},tcp}
14:59:00.279 [info] Reusing listening port for {5443,{0,0,0,0},tcp}
14:59:00.280 [info] ejabberd 15.10 is started in the node ejabberd@291d27d74100
14:59:00.280 [info] Application ejabberd started on node ejabberd@291d27d74100
Updating module specs... Failed RPC connection to the node ejabberd@291d27d74100: timeout

Commands to start an ejabberd node:
  start    Start an ejabberd node in server mode
  debug    Attach an interactive Erlang shell to a running ejabberd node
  iexdebug Attach an interactive Elixir shell to a running ejabberd node
  live     Start an ejabberd node in live (interactive) mode
  iexlive  Start an ejabberd node in live (interactive) mode, within an Elixir shell

Optional parameters when starting an ejabberd node:
  --config-dir dir   Config ejabberd:    //etc/ejabberd
  --config file      Config ejabberd:    //etc/ejabberd/ejabberd.yml
  --ctl-config file  Config ejabberdctl: //etc/ejabberd/ejabberdctl.cfg
  --logs dir         Directory for logs: //var/log/ejabberd
  --spool dir        Database spool dir: /opt/ejabberd/database/ejabberd@291d27d74100
  --node nodename    ejabberd node name: ejabberd@291d27d74100
```

**Comment by rroemhild** [comment]
Hey, it seems that the RPC connection breaks some times. I'll look into this and in the meantime you can add the EJABBERD_SKIP_MODULES_UPDATE environment variable to skip updating modules:

```
docker run -t -i -p 5222 -p 5269 -p 5280 -e "XMPP_DOMAIN=foo.com" -e "EJABBERD_SKIP_MODULES_UPDATE=true" rroemhild/ejabberd
``` 

If you want do update the modules specs you can try to do this after ejabberd is up:

```
docker exec CONTAINER ejabberdctl modules_update_specs
```

**Comment by patrickcorrigan** [comment]
Thank you very much for the quick response. I even able to update the modules after a few tries once the container was up. Thank you very much.

**Comment by rotblade** [comment]
I have the exactly same issue. I was able to start the ejabberd after adding EJABBERD_SKIP_MODULES_UPDATE=true.  However, I'm keeping on receiving the same TIMEOUT error when run "ocker exec CONTAINER ejabberdctl modules_update_specs" after the container up.

>Generating` ejabberd config file...
Generating ejabberdctl config file...
Starting ejabberd...
tail: cannot open ‘/var/log/ejabberd/crash.log’ for reading: No such file or directory
tail: cannot open ‘/var/log/ejabberd/error.log’ for reading: No such file or directory
tail: cannot open ‘/var/log/ejabberd/erlang.log’ for reading: No such file or directory
tail: ‘/var/log/ejabberd/crash.log’ has been replaced with a remote file. giving up on this name
tail: ‘/var/log/ejabberd/error.log’ has been replaced with a remote file. giving up on this name
16:10:51.426 [info] Application lager started on node ejabberd@xmpp1
16:10:51.435 [info] Application crypto started on node ejabberd@xmpp1
16:10:51.445 [info] Application sasl started on node ejabberd@xmpp1
16:10:51.458 [info] Application asn1 started on node ejabberd@xmpp1
16:10:51.458 [info] Application public_key started on node ejabberd@xmpp1
16:10:51.469 [info] Application ssl started on node ejabberd@xmpp1
16:10:51.474 [info] Application fast_yaml started on node ejabberd@xmpp1
16:10:51.484 [info] Application fast_tls started on node ejabberd@xmpp1
16:10:51.490 [info] Application fast_xml started on node ejabberd@xmpp1
16:10:51.493 [info] Application stringprep started on node ejabberd@xmpp1
16:10:51.498 [info] Application cache_tab started on node ejabberd@xmpp1
16:10:51.511 [info] Application elixir started on node ejabberd@xmpp1
16:10:51.673 [info] Application mnesia started on node ejabberd@xmpp1
16:10:52.341 [info] Application inets started on node ejabberd@xmpp1
16:10:53.115 [info] FQDN used to check DIGEST-MD5 SASL authentication: <<"xmpp1.example.com">>
16:10:53.117 [info] LDAP connection on xxx.xxx.xxx.xxx:389
16:10:53.118 [info] LDAP connection on xxx.xxx.xxx.xxx:389
16:10:53.139 [info] LDAP connection on xxx.xxx.xxx.xxx:389
16:10:53.206 [info] Application iconv started on node ejabberd@xmpp1
16:10:53.207 [info] Reusing listening port for {4560,{0,0,0,0},tcp}
16:10:53.207 [info] Reusing listening port for {5222,{0,0,0,0},tcp}
16:10:53.207 [info] Reusing listening port for {5269,{0,0,0,0},tcp}
16:10:53.208 [info] Reusing listening port for {5280,{0,0,0,0},tcp}
16:10:53.208 [info] Reusing listening port for {5443,{0,0,0,0},tcp}
16:10:53.208 [info] ejabberd 16.09 is started in the node ejabberd@xmpp1
16:10:53.208 [info] Application ejabberd started on node ejabberd@xmpp1

>$ docker exec xmpp1_ejabberd ejabberdctl modules_update_specs
Failed RPC connection to the node ejabberd@xmpp1: timeout

>Commands to start an ejabberd node:
  start      Start an ejabberd node in server mode
  debug      Attach an interactive Erlang shell to a running ejabberd node
  iexdebug   Attach an interactive Elixir shell to a running ejabberd node
  live       Start an ejabberd node in live (interactive) mode
  iexlive    Start an ejabberd node in live (interactive) mode, within an Elixir shell
  foreground Start an ejabberd node in server mode (attached)

>Optional parameters when starting an ejabberd node:
  --config-dir dir   Config ejabberd:    //etc/ejabberd
  --config file      Config ejabberd:    //etc/ejabberd/ejabberd.yml
  --ctl-config file  Config ejabberdctl: //etc/ejabberd/ejabberdctl.cfg
  --logs dir         Directory for logs: //var/log/ejabberd
  --spool dir        Database spool dir: /opt/ejabberd/database/ejabberd
  --node nodename    ejabberd node name: ejabberd

>$ docker exec -it xmpp1_ejabberd /bin/bash
ejabberd@xmpp1:$ ejabberdctl status
The node ejabberd@xmpp1 is started with status: started
ejabberd 16.09 is running in that node
ejabberd@xmpp1:$ epmd -names
epmd: up and running on port 4369 with data:
name ejabberd at port 35477

**Comment by rotblade** [comment]
My docker-compose.yml file to run ejabberd.

> version: '2'
services:
  ejabberd:
    image: rroemhild/ejabberd
    container_name: xmpp1_ejabberd
    ports:
      - 5222:5222
      - 5269:5269
      - 5280:5280
      - 5443:5443
      - 4560:4560
    hostname: xmpp1.cn.domain.com
    environment:
      - XMPP_DOMAIN=cn.domain.com
      - ERLANG_NODE=ejabberd
      - EJABBERD_AUTH_METHOD=ldap
      - EJABBERD_LDAP_SERVERS=ldap_server_ip
      - EJABBERD_LDAP_ENCRYPT=none
      - EJABBERD_LDAP_PORT=389
      - EJABBERD_LDAP_ROOTDN=CN=ldapbind,OU=Users,OU=CNXXX,OU=CN,DC=XXX,DC=XXX,DC=XXX,DC=com
      - EJABBERD_LDAP_PASSWORD=ldapbind_password
      - EJABBERD_LDAP_BASE=DC=xxx,DC=xxx,DC=xxx,DC=com
      - EJABBERD_LDAP_UIDS=mail:%u@cn.domain.com
      - EJABBERD_LDAP_FILTER=(memberOf=*)
      - EJABBERD_SKIP_MODULES_UPDATE=true
      - EJABBERD_ADMINS=admin@cn.domain.com
      - TZ=Asia/Shanghai
    volumes:
      - ./conf:/opt/ejabberd/conf
      - ejabberd-ssl:/opt/ejabberd/ssl
      - ejabberd-backup:/opt/ejabberd/backup
      - ejabberd-upload:/opt/ejabberd/upload
      - ejabberd-database:/opt/ejabberd/database
    networks:
      - docker_ejabberd

networks:
  docker_ejabberd:
    external: true

volumes:
  ejabberd-ssl:
    external: true
  ejabberd-backup:
    external: true
  ejabberd-upload:
    external: true
  ejabberd-database:
    external: true

**Comment by umutcetinkaya** [comment]
I could not find a solution for the container to start itself constantly. Did you find it? I do not understand why it's closing. :(
