### ISSUE TITLE
Cannot start creating config file

### ISSUE THREAD

**Issue by guillemsola** [rroemhild/docker-ejabberd#75]
Hi,

Tried with a couple of versions. Image starts but it suddenly fails. I can see this in the logs

	writing ssl cert and private key to '/opt/ejabberd/ssl/host.pem'...
	Missing ssl cert for your xmpp domain. Generating snakeoil ssl cert for example.cat...
	Generating a 2048 bit RSA private key
	....+++
	..............................+++
	writing new private key to '/tmp/selfsigned.key'
	-----
	Writing ssl cert and private key to '/opt/ejabberd/ssl/example.cat.pem'...
	Generating ejabberd config file...
	Traceback (most recent call last):
	  File "<string>", line 7, in <module>
	  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
		return self.environment.handle_exception(exc_info, True)
	  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
		reraise(exc_type, exc_value, tb)
	  File "<template>", line 133, in top-level template code
	UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 11: ordinal not in range(128)

**Comment by rroemhild** [comment]
Hi, I can't reproduce this error. How do you start the container? Do you use volumes or your own config templates? Does the Quick Start example work for you?

**Comment by guillemsola** [comment]
My apologies,

As you confirmed me it was working I double checked my run parameters and found a weird character passed as env var.

This was throwing an error as ejabberd was not able to parse it.
