### ISSUE TITLE
Best way to run command after setup.

### ISSUE THREAD

**Issue by patrickcorrigan** [rroemhild/docker-ejabberd#89]
Hello @rroemhild. I'm very happy with this docker image. Thank you. What is killing me however is running an automated command after every startup. I've tried CMD with sleep timers. I've tried adding to the start up scripts. I cannot seem to get it to work. What would your suggestion be?

Thank you very much.

**Comment by rroemhild** [comment]
Hi @patrickcorrigan, I would suggest to run your command from the post run-scripts. The post-sciprt file must be executable.

```
$ touch 70_get_hostname.sh
$ chmod +x 70_get_hostname.sh
```

Content of 70_get_hostname.sh:
```
#!/bin/bash
set -e
echo -n "Hostname: " 
hostname
```

Dockerfile for your image:
```
FROM rroemhild/ejabberd
COPY 70_get_hostname.sh /opt/ejabberd/scripts/post/70_get_hostname.sh
```

Build and run your image:
```
$ docker build -t ejabberd_test .
$ docker run --rm -P ejabberd_test
```

**Comment by patrickcorrigan** [comment]
That worked perfectly. Thank you very much and thank you for the quick response Rafael. 

Have a nice weekend.

Kind regards, 
Patrick
