### ISSUE TITLE
Ignore config generation if conf folder contains them

### ISSUE THREAD

**Issue by sudohippie** [rroemhild/docker-ejabberd#91]
Hi @rroemhild, thanks for this image. Greatly appreciate it.

As an improvement, in addition to passing in env variables in the run command it would be great if the container could read the config files from the host machine directly (via mount). By doing something like
```
docker run -v /opt/volumes/ejabberd/conf:/opt/ejabberd/conf ...
```
Where /opt/volumes/ejabberd/conf on my host machine would look like:
```
/opt/volumes/ejabberd/conf/
├── ejabberdctl.cfg
├── ejabberd.yml
└── inetrc
```

This would enable easy manipulation of configurations with out touching the templates and addition of new variables.

The fix seems simple and I can submit a PR if you are willing to take it.

**Comment by rroemhild** [comment]
Hi @sudohippie, I'm glad to hear that you like this image. I think that is a good point and I'll merge an PR from you. Regards
