### ISSUE TITLE
erlang cookie

### ISSUE THREAD

**Issue by joshuacox** [rroemhild/docker-ejabberd#97]
Anyone using the  "ERLANG_COOKIE"  environment VAR?  I'm getting a permission denied error:
```
Set erlang cookie to blhakljdkadfksks...
/opt/ejabberd/scripts/pre/10_erlang_cookie.sh: line 12: /opt/ejabberd/.erlang.cookie: Permission denied
```

I'm not mounting any volumes at the moment, so the /opt/ejabberd directory is straight from the docker image.

**Comment by rroemhild** [comment]
Hi, just run a short test with `rroemhild/ejabberd:latest` and the erlang cookie file could be written. What version/tag do you use?

**Comment by joshuacox** [comment]
I'm using latest, this seems to be exclusive to docker containers running debian jessie and aufs, closing as I don't believe is wrong with this image in particular

**Comment by joshuacox** [comment]
well nevermind I can duplicate on ubuntu trusty upgrade and using overlayfs, with this:
```
docker run -d \
        --name "ejabberd" \
        --cidfile="ejabberdCID" \
        -p 5222:5222 \
        --link freeipa:freeipa \
        -p 5269:5269 \
        --restart=always \
        -p 5280:5280 \
        -p 5443:5443 \
        -p 4369:4369 \
        -h belle.southfumar.com \
        -e "XMPP_DOMAIN=southfumar.com" \
        -e "ERLANG_NODE=ejabberd" \
        -e "TZ=America/Chicago" \
        -e "EJABBERD_ADMIN=admin@example.com" \
        -e "EJABBERD_AUTH_METHOD=ldap" \
        -e "EJABBERD_WEB_ADMIN_SSL=true" \
        -e "EJABBERD_STARTTLS=true" \
        -e "EJABBERD_S2S_SSL=true" \
        -e "EJABBERD_LDAP_SERVERS=freeipa" \
        -e "EJABBERD_LDAP_ROOTDN=uid=ejabberd,cn=sysaccounts,cn=etc,dc=example,dc=com" \
        -e "EJABBERD_LDAP_PASSWORD=RANDOMPASS" \
        -e "EJABBERD_LDAP_DEREF_ALIASES=always" \
        -e "EJABBERD_LDAP_BASE=ou=jabber_users,dc=example,dc=com" \
        -e "EJABBERD_LDAP_FILTER=" \
        -e "EJABBERD_LDAP_UIDS=uid" \
        -e "ERLANG_COOKIE=T5TggmN5VPlReSqtl9x0" \
        rroemhild/ejabberd
```

any clue what I might be doing wrong?  the whole setup can be near duplicated using:
https://github.com/joshuacox/mkFreeIPA
given that you have PTR records set

**Comment by rroemhild** [comment]
This could be a kernel Problem. I found something similar but with different Kernel version https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1555997.

Did you download the image before switching to overlayFS? Then maybe you have to remove the image and pull again.

**Comment by rroemhild** [comment]
I have no System with Ubuntu and Kernel 3.19 to reproduce this but you can try https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1555997/comments/3 to test overlayFS with chmod.

**Comment by joshuacox** [comment]
I tried the little test without issue.  
```
$ mkdir /tmp/lower /tmp/upper /tmp/work /tmp/merged
$ sudo mount -t overlay overlay -olowerdir=/tmp/lower,upperdir=/tmp/upper,workdir=/tmp/work /tmp/merged
$ sudo touch /tmp/merged/testfile
$ sudo chown $USER:$USER /tmp/merged/testfile
$ $ chmod +x /tmp/merged/testfile
```

Out of curiosity on which distro do you run your containers?

**Comment by joshuacox** [comment]
Okay I also duplicated on centos7:

```
uname -a
Linux ds01.example.com 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-302025371-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.597 GB
 Data Space Total: 107.4 GB
 Data Space Available: 57.78 GB
 Metadata Space Used: 2.847 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 1.796 GiB
Name: ds01.example.com
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Comment by joshuacox** [comment]
looking through that docker info I realized my cloud instance was provisioned with XFS, this might very well be the root of the issue here

**Comment by rroemhild** [comment]
I'm curious about it. I've tested on Fedora 23 (Kernel 4.4.9, ext4), Ubuntu 12.02 with (Kernel 3.13.0, ext4) and CoreOS stable.

**Comment by joshuacox** [comment]
ok I've tested this on a completely different cloud provider  ([codero](http://www.codero.com/)) and everything works fine in terms of the cookie (I do still have some issues working out the LDAP server stuff but its unrelated). I'll not embarass the other provider publicly.  So I'm closing this issue.  Thanks for the sanity check
